
skillMetadata:
  sections:
    - name: LED Pattern
      fields:
        - name: LED_pattern
          type: select
          label: LED Pattern
          options: Alexa Pattern|alexa_pattern; Google Home|google_home
          value: "alexa_pattern"

